import  selenium
from selenium import webdriver
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select

driver= webdriver.Chrome(executable_path='C:/Users/hp/PycharmProjects/untitled10/Drivers/chromedriver.exe')
driver.get("https://www.google.com/")
driver.maximize_window()
#Search for flipkart in google search
driver.find_element_by_xpath("//input[@title='Search']").clear()
driver.find_element_by_xpath("//input[@title='Search']").send_keys("flipkart")
action=ActionChains(driver)
driver.find_element_by_xpath("//input[@title='Search']").click()
driver.implicitly_wait(5)
driver.find_element_by_xpath('//input[@value="Google Search"]').click()
driver.find_element_by_xpath('/html[1]/body[1]/div[7]/div[2]/div[10]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]/h3[1]').click()
driver.find_element_by_xpath('/html[1]/body[1]/div[2]/div[1]/div[1]/button[1]').click()
driver.implicitly_wait(5)

action1=driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[1]/div[2]/div[1]/div[1]/span[2]')
action.double_click(action1).perform()
action2=driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/a[8]')
action.double_click(action2).perform()
driver.get("https://www.flipkart.com/home-kitchen/home-appliances/air-conditioners/window~type/pr?sid=j9e%2Cabm%2Cc54&otracker=nmenu_sub_TVs%20%26%20Appliances_0_Window%20ACs")
driver.execute_script("window.scrollTo(0,10)")
driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/a[1]/div[1]/div[2]/div[1]/span[1]").click()
driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[4]/div[1]/div[1]/div[1]/a[1]/div[1]/div[2]/div[1]/span[1]/div[1]/label[1]/div[1]").click()
driver.implicitly_wait(10)

driver.execute_script("window.scrollTo(0,200)")
driver.find_element_by_xpath("//span[contains(text(),'COMPARE')]").click()
driver.get("https://www.flipkart.com/air_conditioner_new/compare?ids=ACNFQ32UZGYZHKTY,ACNFGGUDTYGMESZP&otracker=compare_product_2")
driver.implicitly_wait(5)
driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]").click()
driver.find_element_by_xpath("//div[@class='LG4KV_']//input[@placeholder='Choose Brand']").send_keys("Samsung")
driver.find_element_by_xpath("//div[contains(@class,'row')]//div[1]//div[1]//div[2]//div[2]//input[1]").click()
driver.find_element_by_xpath("//div[@class='LG4KV_']//div[@class='_2KISpu'][contains(text(),'Samsung')]").click()

driver.implicitly_wait(5)
driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]").click()
driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]").click()

driver.implicitly_wait(10)

product1_name= driver.find_element_by_xpath("//div[contains(@class,'_1k1axX _1DLH7w')]//div[2]//a[1]")
print("Product 1 Name:",product1_name.text)
product1_Price= driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]")
print("Product 1 Price:",product1_Price.text)
product2_name=driver.find_element_by_xpath("//div[@class='_1k1axX _1DLH7w']//div[3]//a[1]")
print("Product2 Name:",product2_name.text)
product2_price= driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]")
print("Product Price 2",product2_price.text)
product3_name= driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/a[1]")
print("Product 3 Name",product3_name.text)
product3_price=driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[4]/div[1]/div[1]/div[1]")
print("Product 3 Price",product3_price.text)
driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[3]/div[5]/div[2]/button[1]").click()
driver.back()
driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[3]/div[5]/div[3]/button[1]").click()
driver.back()
driver.get("https://www.flipkart.com/air_conditioner_new/compare?ids=ACNFU3XZD6XXZ8NZ,ACNF2425FJSWJVE6,ACNFGGUDTYGMESZP&otracker=compare_product_3")
driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[3]/div[5]/div[4]/button[1]").click()
driver.implicitly_wait(10)
driver.get("https://www.flipkart.com/viewcart?otracker=PP_GoToCart")
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/input[1]').clear()
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/input[1]').send_keys("382481")
driver.find_element_by_xpath("//span[@class='_2m9c-p']").click()
